eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: configClient
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
env:
  dev3211232
server:
  port: 8764
girl:
  name: lili
  age: 19
